// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type City struct {
	ID     int64
	Name   string
	IsUsed bool
}

type House struct {
	ID                   int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Title                string
	CityID               int64
	Address              string
	Price                int64
	Surface              int64
	Rooms                int64
	Bedrooms             int64
	Bathrooms            int64
	Floors               int64
	ConstructionYear     int64
	HouseType            string
	LandSurface          int64
	HasGarage            bool
	OutdoorParkingSpaces int64
	MainPhoto            string
	Notes                string
	CityName             string
}

type PublicationURL struct {
	ID              int64
	HouseID         int64
	URL             string
	PublicationDate time.Time
}
