// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type City struct {
	ID   int64
	Name string
}

type House struct {
	ID                   int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Title                string
	CityID               int64
	Address              sql.NullString
	Price                int64
	Surface              int64
	Rooms                sql.NullInt64
	Bedrooms             sql.NullInt64
	Bathrooms            sql.NullInt64
	Floors               sql.NullInt64
	ConstructionYear     sql.NullInt64
	HouseType            string
	LandSurface          sql.NullInt64
	HasGarage            sql.NullBool
	OutdoorParkingSpaces sql.NullInt64
	MainPhoto            sql.NullString
	Notes                sql.NullString
}

type PublicationURL struct {
	ID              int64
	HouseID         int64
	URL             string
	PublicationDate time.Time
	IsMain          bool
}
